#############################################################################
# Generated by PAGE version 4.10
# in conjunction with Tcl version 8.6
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m58" -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 1920x1051+0+0
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Mission Command"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can38 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can38" "GyroX" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can39 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can39" "GyroY" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can40 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can40" "GyroZ" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can41 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can41" "AccelX" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can42 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can42" "AccelY" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can43 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can43" "AccelZ" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can44 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can44" "MagX" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can45 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can45" "MagY" vTcl:WidgetProc "Toplevel1" 1
    canvas $top.can46 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 221 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 531 
    vTcl:DefineAlias "$top.can46" "MagZ" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes48 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Current Status} -width 165 
    vTcl:DefineAlias "$top.mes48" "StatusHeader" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes50 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Heading: -textvariable {} -width 65 
    vTcl:DefineAlias "$top.mes50" "HDG" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes51 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Pitch: -width 65 
    vTcl:DefineAlias "$top.mes51" "Pitch" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes52 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Roll: -width 65 
    vTcl:DefineAlias "$top.mes52" "Roll" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes53 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Upwards Accel:} -width 105 
    vTcl:DefineAlias "$top.mes53" "YAcc" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes54 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Roll Rate:} -width 65 
    vTcl:DefineAlias "$top.mes54" "RollR" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes55 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Yaw Rate:} -width 65 
    vTcl:DefineAlias "$top.mes55" "YawRate" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes56 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Pitch Rate:} -width 65 
    vTcl:DefineAlias "$top.mes56" "PitchRate" vTcl:WidgetProc "Toplevel1" 1
    message $top.mes57 \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Current Temp:} -width 105 
    vTcl:DefineAlias "$top.mes57" "PitchRate1" vTcl:WidgetProc "Toplevel1" 1
    menu $top.m58 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can38 \
        -in $top -x 20 -y 20 -width 531 -relwidth 0 -height 221 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.can39 \
        -in $top -x 580 -y 20 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can40 \
        -in $top -x 1140 -y 20 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can41 \
        -in $top -x 20 -y 290 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can42 \
        -in $top -x 580 -y 290 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can43 \
        -in $top -x 1140 -y 290 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can44 \
        -in $top -x 20 -y 560 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can45 \
        -in $top -x 580 -y 560 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.can46 \
        -in $top -x 1140 -y 560 -width 531 -height 221 -anchor nw \
        -bordermode inside 
    place $top.mes48 \
        -in $top -x 1790 -y 30 -width 165 -relwidth 0 -height 33 -relheight 0 \
        -anchor center -bordermode ignore 
    place $top.mes50 \
        -in $top -x 1700 -y 50 -width 65 -relwidth 0 -height 33 -relheight 0 \
        -anchor nw -bordermode inside 
    place $top.mes51 \
        -in $top -x 1700 -y 80 -width 65 -height 33 -anchor nw \
        -bordermode inside 
    place $top.mes52 \
        -in $top -x 1700 -y 110 -width 65 -height 33 -anchor nw \
        -bordermode inside 
    place $top.mes53 \
        -in $top -x 1680 -y 140 -width 105 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode inside 
    place $top.mes54 \
        -in $top -x 1700 -y 170 -width 65 -height 33 -anchor nw \
        -bordermode inside 
    place $top.mes55 \
        -in $top -x 1700 -y 200 -width 65 -height 33 -anchor nw \
        -bordermode inside 
    place $top.mes56 \
        -in $top -x 1700 -y 230 -width 65 -height 33 -anchor nw \
        -bordermode inside 
    place $top.mes57 \
        -in $top -x 1680 -y 260 -width 105 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode inside 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

  set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

